# Generated by Django 4.2.7 on 2023-12-07 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('sucursal', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='especialidad',
            old_name='doctor',
            new_name='nombre_doctor',
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('email', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.direccion')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.doctor')),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.especialidad'),
        ),
    ]
